import { auth, onAuthStateChanged, reff,updateDoc, onValue, dbd, doc, getDoc, db, collection, getDocs, signOut } from "./config.js";

var uid = null;
onAuthStateChanged(auth, async (user) => {
  if (user) {

    uid = user.uid;

    const docRef = collection(db, "concern");
    const docSnap = await getDocs(docRef);
    if (docSnap.empty) {
      console.log("No transactions found.");
      return;
    }
    console.log("Transactions found:", docSnap.docs.length);
    const transactions = [];

console.log("Transactions found:", docSnap.docs[0].data());
   renderTransactions(docSnap.docs.map(doc => ({
        ...doc.data(),
        id: doc.id // Include the document ID
    })));   

    // ...
  } else {
    // User is signed out
    // ...
    window.location.href = "../login.html";
  }
});




function renderTransactions(data) {
    const tbody = document.getElementById("transactionBody");
    tbody.innerHTML = ""; // Clear previous rows
    data.forEach(item => {
        // Handle Firestore Timestamp to date string
        let dateStr = item.createdAt.toDate().toLocaleDateString();
        if (item.paid_at && typeof item.paid_at.toDate === "function") {
            const d = item.paid_at.toDate();
            dateStr = d.toLocaleDateString();
        } else if (item.timestamp && typeof item.timestamp.toDate === "function") {
            const d = item.timestamp.toDate();
            dateStr = d.toLocaleDateString();
        } else if (item.date) {
            dateStr = item.date;
        }

        // Status and icon logic
        let icon = item.status === "paid" || item.status === "Success" ? "✔" : "−";
        let rowClass = icon === "✔" ? "tick-row" : "";

        // Transaction ID
        let id =  item.id || "";

        // Source
        let status = item.status || item.status || "";

        // Amount
        let amount = item.amount || "";

        const row = document.createElement("tr");
        if (rowClass) row.classList.add(rowClass);
        row.innerHTML = `
            <td><a>${id}</a></td>
            <td>${dateStr}</td>
            <td><span class="status-success">${status}</span></td>
            <td><button class="view-btn" data-id='${item.id}'>View</button></td>
        `;

        // Add event listener to the "View" button
        row.querySelector('.view-btn').addEventListener('click', () => {
            // Create or select the dialog box
            let dialog = document.getElementById('transaction-dialog');
            if (!dialog) {
            dialog = document.createElement('dialog');
            dialog.id = 'transactionDialog';
            document.body.appendChild(dialog);
            }
            // Fill dialog with details
            dialog.innerHTML = `
                <div style="padding: 24px; min-width: 340px; font-family: Arial, sans-serif;">
                    <h2 style="margin-top:0; color:#1976d2;">Support Ticket Details</h2>
                    <table style="width:100%; border-collapse:collapse; margin-bottom:16px; font-size:15px;">
                        <tr>
                            <th style="text-align:left; padding:4px 8px; color:#666;">Ticket ID</th>
                            <td style="padding:4px 8px;">${item.transactionId || item.id || ""}</td>
                        </tr>
                        <tr>
                            <th style="text-align:left; padding:4px 8px; color:#666;">Status</th>
                            <td style="padding:4px 8px;">${item.status || ""}</td>
                        </tr>
                        <tr>
                            <th style="text-align:left; padding:4px 8px; color:#666;">Type</th>
                            <td style="padding:4px 8px;">${item.type || ""}</td>
                        </tr>
                        <tr>
                            <th style="text-align:left; padding:4px 8px; color:#666;">Subject</th>
                            <td style="padding:4px 8px;">${item.subject || ""}</td>
                        </tr>
                        <tr>
                            <th style="text-align:left; padding:4px 8px; color:#666;">Message</th>
                            <td style="padding:4px 8px; white-space:pre-line;">${item.message || ""}</td>
                        </tr>
                        <tr>
                            <th style="text-align:left; padding:4px 8px; color:#666;">Generated By</th>
                            <td style="padding:4px 8px;">${item.generatedby || ""}</td>
                        </tr>
                        <tr>
                            <th style="text-align:left; padding:4px 8px; color:#666;">User ID</th>
                            <td style="padding:4px 8px;">${item.userId || ""}</td>
                        </tr>
                        <tr>
                            <th style="text-align:left; padding:4px 8px; color:#666;">Created At</th>
                            <td style="padding:4px 8px;">
                                ${
                                    item.createdAt && typeof item.createdAt.toDate === "function"
                                        ? item.createdAt.toDate().toLocaleString()
                                        : ""
                                }
                            </td>
                        </tr>
                        <tr>
                            <th style="text-align:left; padding:4px 8px; color:#666;">Updated At</th>
                            <td style="padding:4px 8px;">
                                ${
                                    item.updatedAt && typeof item.updatedAt.toDate === "function"
                                        ? item.updatedAt.toDate().toLocaleString()
                                        : ""
                                }
                            </td>
                        </tr>
                    </table>
                    <button id="closeDialogBtn" style="padding:8px 20px; background:#1976d2; color:#fff; border:none; border-radius:4px; cursor:pointer;">Close</button>
                    <button id="completeTicketBtn" style="padding:8px 20px; background:#43a047; color:#fff; border:none; border-radius:4px; cursor:pointer; margin-left:10px;">Mark as Completed</button>
                </div>
            `;

            // Complete Ticket button logic
            dialog.querySelector('#completeTicketBtn').onclick = async () => {
                const ticketId = item.id;
                if (!ticketId) return;
                try {
                    const ticketRef = doc(db, "concern", ticketId);
                    await updateDoc(ticketRef, {
                        status: "Completed",
                        updatedAt: new Date()
                    });
                    alert("Ticket marked as completed.");
                    dialog.close();
                    // Optionally, refresh the table
                    location.reload();
                } catch (err) {
                    alert("Failed to update ticket: " + err.message);
                }
            };
            dialog.showModal();
            dialog.querySelector('#closeDialogBtn').onclick = () => dialog.close();
        });
        tbody.appendChild(row);
    });
}
renderTransactions();
document.getElementById("view_details").addEventListener("click",()=>{
    document.getElementById()
});

